6 RoR/ajax-example/config/routes.rb
Rails.application.routes.draw do
  get 'implicit/in'
  get 'implicit/ajax'
  get 'explicit/in'
  get 'explicit/ajax'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

6 RoR/ajax-example/app/controllers/explicit_controller.rb
class ExplicitController < ApplicationController
  def in; end

  def ajax
    m = params[:m]
    @result = if !m || m.empty?
                'Введите число'
              else
                reverse_number m
              end
    respond_to do |format|
      format.json { render json: { result: @result } }
    end
  end

  private

  def reverse_number(number)
    number.to_i(10).to_s(2).reverse.to_i(2)
  end
end

6 RoR/ajax-example/app/controllers/implicit_controller.rb
class ImplicitController < ApplicationController
  def in; end

  def ajax
    m = params[:m]
    @result = if !m || m.empty?
                'Введите число'
              else
                reverse_number m
              end
    respond_to do |format|
      format.js { render 'in.js.erb' }
    end
  end

  private

  def reverse_number(number)
    number.to_i(10).to_s(2).reverse.to_i(2)
  end
end

6 RoR/ajax-example/app/helpers/explicit_helper.rb
module ExplicitHelper
end

6 RoR/ajax-example/app/helpers/implicit_helper.rb
module ImplicitHelper
end

6 RoR/ajax-example/app/views/explicit/in.html.erb
<h1>Задание</h1>

<p>Дано натуральное число m. Написать программу, определяющую такое
  натуральное число n, что двоичная запись числа n получается из двоичной
  записи числа m изменением порядка цифр на обратный порядок их
  следования. Например: 6 = 110 , а 3 = 011. Вывести на печать числа и
  их двоичное представление.</p>

<h2>Форма ввода с явным AJAX</h2>

<div id="explicit__container">
  <%= form_with id: 'explicit__form', method: :get, url: explicit_ajax_path do |form| %>
    <%= form.number_field :m, placeholder: 'Введите число', min: 1 %>
    <%= form.submit 'Отправить форму' %>
  <% end %>

  <p id="explicit__result"></p>
</div>

6 RoR/ajax-example/app/views/implicit/in.html.erb
<h1>Задание</h1>

<p>Дано натуральное число m. Написать программу, определяющую такое
  натуральное число n, что двоичная запись числа n получается из двоичной
  записи числа m изменением порядка цифр на обратный порядок их
  следования. Например: 6 = 110 , а 3 = 011. Вывести на печать числа и
  их двоичное представление.</p>

<h2>Форма ввода с неявным AJAX</h2>

<div id="implicit__container">
  <%= form_with id: 'implicit__form', method: :get, url: implicit_ajax_path do |form| %>
    <%= form.number_field :m, placeholder: 'Введите число', min: 1 %>
    <%= form.submit 'Отправить форму' %>
  <% end %>

  <p id="implicit__result"></p>
</div>

6 RoR/ajax-example/app/views/implicit/in.js.erb
document.querySelector('#implicit__result').innerHTML = '<%= escape_javascript @result.to_s %>'

6 RoR/ajax-example/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>