6 RoR/rspec-example/config/routes.rb
Rails.application.routes.draw do
  get 'example/in'
  get 'example/out'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

6 RoR/rspec-example/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

6 RoR/rspec-example/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

6 RoR/rspec-example/app/controllers/example_controller.rb
class ExampleController < ApplicationController
  def in; end

  def out
    m = params[:m]
    @result = if !m || m.empty?
                'Введите число'
              else
                reverse_number m
              end
  end

  private

  def reverse_number(number)
    number.to_i(10).to_s(2).reverse.to_i(2)
  end
end

6 RoR/rspec-example/app/helpers/application_helper.rb
module ApplicationHelper
end

6 RoR/rspec-example/app/helpers/example_helper.rb
module ExampleHelper
end

6 RoR/rspec-example/app/views/example/in.html.erb
<h1>Задание</h1>

<p>Дано натуральное число m. Написать программу, определяющую такое
  натуральное число n, что двоичная запись числа n получается из двоичной
  записи числа m изменением порядка цифр на обратный порядок их
  следования. Например: 6 = 110 , а 3 = 011. Вывести на печать числа и
  их двоичное представление.</p>

<h2>Форма ввода</h2>

<%= form_with local: true, method: :get, url: example_out_path do |form| %>
  <%= form.number_field :m, placeholder: 'Введите число' %>
  <%= form.submit 'Отправить форму' %>
<% end %>

6 RoR/rspec-example/app/views/example/out.html.erb
<h2>Результат</h2>

<p><%= @result %></p>

<%= link_to 'Назад', example_in_path %>

6 RoR/rspec-example/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RspecExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>